name: Prettier
on:
  push:
    branches:
      - master

jobs:
  prettier:
    name: Prettier

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
        
      - name: Prettier Action
        uses: creyD/prettier_action@v4.2
