name: Code formatting

on:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Format code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx,tailwind.config.cjs,json,html,md}
          commit_message: "style: run prettier"
