name: Code formatting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        run: |
          npm run format:check
          exit_code=$?
          echo "::set-env name=EXIT_CODE::$exit_code" # Armazena o Exit Code em uma variável de ambiente

      - name: Format if isn't already
        if: ${{ env.EXIT_CODE == 1 }} # Prettier: 1 Something wasn’t formatted properly
        run: npm run format

