name: Code formatting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Format if isn't already
        if: ${{ failure() }}
        run: npm run format
